cargo-features = ["resolver"]

[workspace]
members = ["bootloader", "kernel", "kernel/kernel_test_macro", "epiphyllum-structures"]
resolver = "2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"