[unstable]
features=["itarget", "host_dep", "dev_dep"]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[target.x86_64-epiphyllum]
runner = "./runner.py"
